config/routes.rb
Rails.application.routes.draw do
  resources :hospital_analytes
  resources :results
  resources :hospitals
  resources :physicians
  resources :patients
  resources :specimen
  resources :analytes

end

app/models/analyte.rb
class Analyte < ActiveRecord::Base
  has_many :results
  has_many :hospital_analytes
  has_many :hospitals, through: :hospital_analytes
end

app/controllers/analytes_controller.rb
class AnalytesController < ApplicationController
  before_action :set_analyte, only: [:show, :edit, :update, :destroy]

  # GET /analytes
  # GET /analytes.json
  def index
    @analytes = Analyte.all
  end

  # GET /analytes/1
  # GET /analytes/1.json
  def show
  end

  # GET /analytes/new
  def new
    @analyte = Analyte.new
  end

  # GET /analytes/1/edit
  def edit
  end

  # POST /analytes
  # POST /analytes.json
  def create
    @analyte = Analyte.new(analyte_params)

    respond_to do |format|
      if @analyte.save
        format.html { redirect_to @analyte, notice: 'Analyte was successfully created.' }
        format.json { render :show, status: :created, location: @analyte }
      else
        format.html { render :new }
        format.json { render json: @analyte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analytes/1
  # PATCH/PUT /analytes/1.json
  def update
    respond_to do |format|
      if @analyte.update(analyte_params)
        format.html { redirect_to @analyte, notice: 'Analyte was successfully updated.' }
        format.json { render :show, status: :ok, location: @analyte }
      else
        format.html { render :edit }
        format.json { render json: @analyte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytes/1
  # DELETE /analytes/1.json
  def destroy
    @analyte.destroy
    respond_to do |format|
      format.html { redirect_to analytes_url, notice: 'Analyte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analyte
      @analyte = Analyte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analyte_params
      params.require(:analyte).permit(:analyte_name, :result_range)
    end
end

app/helpers/analytes_helper.rb
module AnalytesHelper
end

app/views/analytes/_form.html.erb
<%= form_for(@analyte) do |f| %>
  <% if @analyte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analyte.errors.count, "error") %> prohibited this analyte from being saved:</h2>

      <ul>
      <% @analyte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :analyte_name %><br>
    <%= f.text_field :analyte_name %>
  </div>
  <div class="field">
    <%= f.label :result_range %><br>
    <%= f.text_field :result_range %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/analytes/edit.html.erb
<h1>Editing Analyte</h1>

<%= render 'form' %>

<%= link_to 'Show', @analyte %> |
<%= link_to 'Back', analytes_path %>

app/views/analytes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Analytes</h1>

<table>
  <thead>
    <tr>
      <th>Analyte name</th>
      <th>Result range</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analytes.each do |analyte| %>
      <tr>
        <td><%= analyte.analyte_name %></td>
        <td><%= analyte.result_range %></td>
        <td><%= link_to 'Show', analyte %></td>
        <td><%= link_to 'Edit', edit_analyte_path(analyte) %></td>
        <td><%= link_to 'Destroy', analyte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analyte', new_analyte_path %>

app/views/analytes/new.html.erb
<h1>New Analyte</h1>

<%= render 'form' %>

<%= link_to 'Back', analytes_path %>

app/views/analytes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Analyte name:</strong>
  <%= @analyte.analyte_name %>
</p>

<p>
  <strong>Result range:</strong>
  <%= @analyte.result_range %>
</p>

<%= link_to 'Edit', edit_analyte_path(@analyte) %> |
<%= link_to 'Back', analytes_path %>