config/routes.rb
Rails.application.routes.draw do
  resources :hospital_analytes
  resources :results
  resources :hospitals
  resources :physicians
  resources :patients
  resources :specimen
  resources :analytes

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :specimen
  has_many :hospital_physicians
  has_many :hospitals, through: :hospital_physicians
  has_many :patients

  validates :physician_phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, 
    message: "bad format" }

  #join analytes table from results related to specimen
  #pick results within date range
  #return only distinct analyte names from those results
  def result_analytes
    self.specimen.includes(results: :analyte)
                 .where(results: {reported_at: DateTime.new(2014,1,1)..DateTime.new(2014,4,1)})
                 .pluck('distinct analytes.analyte_name')
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:physician_name, :physician_phone_number, :physician_type)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physician_name %><br>
    <%= f.text_field :physician_name %>
  </div>
  <div class="field">
    <%= f.label :physician_phone_number %><br>
    <%= f.text_field :physician_phone_number %>
  </div>
  <div class="field">
    <%= f.label :physician_type %><br>
    <%= f.text_field :physician_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing Physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Physicians</h1>

<table>
  <thead>
    <tr>
      <th>Physician name</th>
      <th>Physician phone number</th>
      <th>Physician type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.physician_name %></td>
        <td><%= physician.physician_phone_number %></td>
        <td><%= physician.physician_type %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New Physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician name:</strong>
  <%= @physician.physician_name %>
</p>

<p>
  <strong>Physician phone number:</strong>
  <%= @physician.physician_phone_number %>
</p>

<p>
  <strong>Physician type:</strong>
  <%= @physician.physician_type %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>