config/routes.rb
Rails.application.routes.draw do
  resources :hospital_analytes
  resources :results
  resources :hospitals
  resources :physicians
  resources :patients
  resources :specimen
  resources :analytes

end

app/models/hospital_analyte.rb
#association table between hospitals and analytes
class HospitalAnalyte < ActiveRecord::Base
	belongs_to :hospital
	belongs_to :analyte
end

app/controllers/hospital_analytes_controller.rb
class HospitalAnalytesController < ApplicationController
  before_action :set_hospital_analyte, only: [:show, :edit, :update, :destroy]

  # GET /hospital_analytes
  # GET /hospital_analytes.json
  def index
    @hospital_analytes = HospitalAnalyte.all
  end

  # GET /hospital_analytes/1
  # GET /hospital_analytes/1.json
  def show
  end

  # GET /hospital_analytes/new
  def new
    @hospital_analyte = HospitalAnalyte.new
  end

  # GET /hospital_analytes/1/edit
  def edit
  end

  # POST /hospital_analytes
  # POST /hospital_analytes.json
  def create
    @hospital_analyte = HospitalAnalyte.new(hospital_analyte_params)

    respond_to do |format|
      if @hospital_analyte.save
        format.html { redirect_to @hospital_analyte, notice: 'Hospital analyte was successfully created.' }
        format.json { render :show, status: :created, location: @hospital_analyte }
      else
        format.html { render :new }
        format.json { render json: @hospital_analyte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospital_analytes/1
  # PATCH/PUT /hospital_analytes/1.json
  def update
    respond_to do |format|
      if @hospital_analyte.update(hospital_analyte_params)
        format.html { redirect_to @hospital_analyte, notice: 'Hospital analyte was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital_analyte }
      else
        format.html { render :edit }
        format.json { render json: @hospital_analyte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospital_analytes/1
  # DELETE /hospital_analytes/1.json
  def destroy
    @hospital_analyte.destroy
    respond_to do |format|
      format.html { redirect_to hospital_analytes_url, notice: 'Hospital analyte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital_analyte
      @hospital_analyte = HospitalAnalyte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_analyte_params
      params.require(:hospital_analyte).permit(:hospital, :analyte)
    end
end

app/helpers/hospital_analytes_helper.rb
module HospitalAnalytesHelper
end

app/views/hospital_analytes/_form.html.erb
<%= form_for(@hospital_analyte) do |f| %>
  <% if @hospital_analyte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospital_analyte.errors.count, "error") %> prohibited this hospital_analyte from being saved:</h2>

      <ul>
      <% @hospital_analyte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hospital %><br>
    <%= f.text_field :hospital %>
  </div>
  <div class="field">
    <%= f.label :analyte %><br>
    <%= f.text_field :analyte %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospital_analytes/edit.html.erb
<h1>Editing Hospital Analyte</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospital_analyte %> |
<%= link_to 'Back', hospital_analytes_path %>

app/views/hospital_analytes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hospital Analytes</h1>

<table>
  <thead>
    <tr>
      <th>Hospital</th>
      <th>Analyte</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospital_analytes.each do |hospital_analyte| %>
      <tr>
        <td><%= hospital_analyte.hospital %></td>
        <td><%= hospital_analyte.analyte %></td>
        <td><%= link_to 'Show', hospital_analyte %></td>
        <td><%= link_to 'Edit', edit_hospital_analyte_path(hospital_analyte) %></td>
        <td><%= link_to 'Destroy', hospital_analyte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital analyte', new_hospital_analyte_path %>

app/views/hospital_analytes/new.html.erb
<h1>New Hospital Analyte</h1>

<%= render 'form' %>

<%= link_to 'Back', hospital_analytes_path %>

app/views/hospital_analytes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hospital:</strong>
  <%= @hospital_analyte.hospital %>
</p>

<p>
  <strong>Analyte:</strong>
  <%= @hospital_analyte.analyte %>
</p>

<%= link_to 'Edit', edit_hospital_analyte_path(@hospital_analyte) %> |
<%= link_to 'Back', hospital_analytes_path %>